### ISSUE TITLE
Add ability to mark a gist private and vice versa

### ISSUE THREAD

**Issue by jarun** [jdowner/gist#2]
I was going thorough the details. Didn't see any option to mark a gist private or unmark it. In addition to editing capabilities, it would be a good feature to have.

**Comment by jdowner** [comment]
You can specify whether you want to create a private or a public gist but do you mean toggling between the two?

**Comment by jarun** [comment]
Right. Is there a way to toggle between private and public after the gist is created?

**Comment by jdowner** [comment]
I've had a quick look at the API but it wasn't clear if that is publically available. It can obviously done via the website so it is possible. I'll do some more research and see if I can figure something out.

**Comment by jarun** [comment]
It might be. The official Ruby client can mark a gist private:
https://github.com/defunkt/gist#readme

Please check the -p option.

**Comment by jarun** [comment]
On a closer look, I guess that's also a creation-time option.

**Comment by jdowner** [comment]
I talked with github support and they confirm that this is not available in the current API.

**Comment by jarun** [comment]
Thanks for looking into the options!


Regards,

Arun

http://tuxdiary.com/ <http://regexp.co.nr>

**Comment by jdowner** [comment]
@jarun thanks for the write up :) Just wanted to also point out that I have added an 'edit' command to work with the users default editor. It is pretty rudimentary but functional (for me). However, I suspect that it will be useful to have the editor specified as an option in the config file to allow users to customize how their editor is invoked to edit the files. Also, this functionality is now available from 'gist create' so that you can create a gist entirely on the fly.

**Comment by jarun** [comment]
My pleasure! I will update the article. I am a heavy gist user myself and I liked this tool. :)
