### ISSUE TITLE
Possible to create .md files?

### ISSUE THREAD

**Issue by kevinhowbrook** [jdowner/gist#41]
Maybe I'm missing this but is it possible to specify the file format when creating a gist?

**Comment by jdowner** [comment]
Hi Kevin. It turns out that you are not missing anything and that gist does not support this functionality. I'm assuming you're talking about the situation where you enter something like,
```
gist create "foo"
```
it brings up your editor and you enter your markdown and exit. There is another mode where you can enter 1 or more existing files to be put into the gist, e.g.
```
gist create "my gist" foo bar baz
```
Because of this existing functionality I am reluctant to just have the user just append a filename. So I think it would have to be something like,
```
gist create "my gist" --filename foo.md
```
What do you think? Would that work for you?

**Comment by kevinhowbrook** [comment]
Yea that would be PERFECT,
